name: geph4-client-linux-amd64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make dir
      run: mkdir ~/repo && cd ~/repo && git clone https://github.com/geph-official/geph4 && cd $_
    - name: Compile -> geph4-client-linux-amd64
      run: cargo build --release --manifest-path=geph4-client/Cargo.toml
    - name: Rename -> geph4-client-linux-amd64
      run: mv target/release/geph4-client target/release/geph4-client-linux-amd64
    - name: Upload to telegram -> geph4-client-linux-amd64
      run: curl "https://api.telegram.org/bot${{ secrets.TOKEN }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}" -F "document=@target/release/geph4-client-linux-amd64" >/dev/null
